f2dhis2/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'f2dhis2.views.home', name='home'),
    # url(r'^f2dhis2/', include('f2dhis2.foo.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),

    url(r'^$', 'main.views.main', name='home'),
    url(r'^(?P<id_string>[^/]+)/post/(?P<uuid>[^/]+)$',
        'main.views.initiate_formhub_request', name='home'),
    url(r'^dataset-import$',
        'main.views.dataset_import', name='dataset-import'),
    url(r'^datasets$',
    'main.views.show_datasets', name='datasets'),
    url(r'^fh-import$',
        'main.views.formhub_import', name='fh-import'),
    url(r'^fh-forms$',
        'main.views.show_formhub_forms', name='fh-forms'),
    url(r'^process-dqueue$',
        'main.views.process_dataqueue', name='process-queue'),
    url(r'^create-dvs',
        'main.views.create_datavalueset', name='create-dvs'),
    url(r'^match-elements',
        'main.views.match_datavalueset_to_data_elements', name='match-de'),
    url(r'^dvs-elements-form/(?P<dvs_id>[^/]+)$',
        'main.views.get_matchdvsform',
        name='match-de-form'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

main/models.py
from django.db import models
from django.utils import simplejson
from django.utils.translation import ugettext as _


class FormhubService(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_formhub_servicet'
        verbose_name = _(u"Formhub Service")
        verbose_name_plural = _(u"Formhub Services")
        unique_together = ('id_string', 'url')

    id_string = models.CharField(_(u"ID"), max_length=32, null=False)
    url = models.URLField(_(u"URL"), null=False)
    name = models.CharField(_(u"Name"), max_length=100)
    json = models.TextField(_(u"Json"), )
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.id_string)

    def get_form_fields(self):
        y = simplejson.loads(self.json)
        rs = ()
        if y.has_key('children'):
            for v in y['children']:
                rs += ((v['name'], v.get('label', v['name'])),)
        return rs


class OrganizationUnit(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_orgunit'
        verbose_name = _(u"Organization Unit")
        verbose_name_plural = _(u"Organization Units")

    org_unit_id = models.CharField(_(u"ID"), max_length=32)#, unique=True)
    name = models.CharField(_(u"Name"), max_length=100)
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.org_unit_id)


class DataSet(models.Model):

    FREQUENCY_YEARLY = 1
    FREQUENCY_QUARTERLY = 4
    FREQUENCY_MONTHLY = 12
    FREQUENCY_WEEKLY = 52
    FREQUENCY_DAILY = 256

    PERIOD_CHOICES = {'yearly': FREQUENCY_YEARLY,
                      'quarterly': FREQUENCY_QUARTERLY,
                      'monthly': FREQUENCY_MONTHLY,
                      'weekly': FREQUENCY_WEEKLY,
                      'daily': FREQUENCY_DAILY}

    FREQUENCY_CHOICES = (
        (FREQUENCY_DAILY, _(u"Daily")),
        (FREQUENCY_WEEKLY, _(u"Weekly")),
        (FREQUENCY_MONTHLY, _(u"Monthly")),
        (FREQUENCY_QUARTERLY, _(u"Quarterly")),
        (FREQUENCY_YEARLY, _(u"Yearly")),
    )

    class Meta:
        app_label = 'main'
        db_table = 'dhis_data_set'
        verbose_name = _(u"Data Set")
        verbose_name_plural = _(u"Data Sets")

    data_set_id = models.CharField(_(u"ID"), max_length=32, unique=True)
    name = models.CharField(_(u"Name"), max_length=100)
    frequency = models.PositiveIntegerField(choices=FREQUENCY_CHOICES, default=FREQUENCY_MONTHLY)
    organizations = models.ManyToManyField(OrganizationUnit)
    url = models.URLField(_(u"URL"), null=True)
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.data_set_id)

    @classmethod
    def get_frequency(cls, period):
        return cls.PERIOD_CHOICES[period.lower()]


class DataValueSet(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_data_value_set'
        verbose_name = _(u"Data Value Set")
        verbose_name_plural = _(u"Data Value Sets")
        unique_together = ('service', 'data_set')

    service = models.ForeignKey(FormhubService, verbose_name=_(u"Formhub Service"))
    data_set = models.ForeignKey(DataSet, verbose_name=_(u"Data Set"))
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.service, self.data_set)


class DataElement(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_data_element'
        verbose_name = _(u"Data Element")
        verbose_name_plural = _(u"Data Elements")
        unique_together = ('data_set', 'data_element_id')

    data_element_id = models.CharField(_(u"ID"), max_length=32)
    name = models.CharField(_(u"Name"), max_length=100)
    data_set = models.ForeignKey(DataSet, verbose_name=_(u"Data Set"))
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.data_element_id)


class FormDataElement(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_form_data_element'
        verbose_name = _(u"Form Data Element")
        verbose_name_plural = _(u"Form Data Elements")
        unique_together = ('data_value_set', 'data_element')

    data_value_set = models.ForeignKey(DataValueSet, verbose_name=_(u"Data Value Set"))
    data_element = models.ForeignKey(DataElement,verbose_name=_(u"Data Element"))
    form_field = models.CharField(_(u"Form Field"), max_length=32)
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s <=> %s" % (self.data_element, self.form_field)


class DataQueue(models.Model):

    class Meta:
        app_label = 'main'
        db_table = 'dhis_data_queue'
        verbose_name = _(u"Data Queue")
        verbose_name_plural = _(u"Data Queue")

    processed = models.BooleanField(_(u"Processed"), default=False)
    processed_on = models.DateTimeField(_(u"Processed on"), null=True)
    data_id = models.CharField(_(u"Formhub Id"), max_length=32)
    service = models.ForeignKey(FormhubService, verbose_name=_(u"Formhub Service"))
    created_on = models.DateTimeField(_(u"Created on"), auto_now_add=True)
    modified_on = models.DateTimeField(_(u"Modified on"), auto_now=True)

    def __unicode__(self):
        return u"%s - %s" % (self.service, self.data_id)

main/forms.py
import json
from django import forms
from django.db.utils import IntegrityError
from django.forms.models import ModelForm
from django.utils.translation import ugettext as _

from main.models import DataSet, DataElement, FormhubService, OrganizationUnit, DataValueSet
from main.utils import load_from_dhis2, load_form_from_formhub


class DataSetImportForm(forms.Form):
    data_set_url = forms.URLField(label="DHIS2 DataSet URL", required=True)

    def ds_import(self):
        if self.is_valid():
            summary = {}
            cleaned_url = self.cleaned_data['data_set_url']
            if not cleaned_url.endswith('.json'):
                cleaned_url += '.json'
            status, ds_data = load_from_dhis2(cleaned_url)
            if status == 200:
                data = json.loads(ds_data)
                if not isinstance(data, dict):
                    return False
                # period
                frequency = DataSet.get_frequency(data['periodType'])
                try:
                    ds = DataSet(data_set_id=data['id'],
                        name=data['name'],
                        frequency=frequency,
                        url=cleaned_url.replace('.json', ''))
                    ds.save()
                except IntegrityError, e:
                    return {
                        'ds_status':
                            _(u"%(dataset)s has already been added." %\
                              {'dataset': data['name']})}
                for de in data['dataElements']:
                    element = DataElement(data_element_id=de['id'],
                        name=de['name'],
                        data_set=ds)
                    element.save()
                for orgunit in data['organisationUnits']:
                    org, created = OrganizationUnit.objects.get_or_create(org_unit_id=orgunit['id'],
                        name=orgunit['name'])
                    #org.save()
                    ds.organizations.add(org)
                summary['dataSet'] = ds
                summary['dataElements'] = data['dataElements'].__len__()
                summary['orgUnits'] = data['organisationUnits'].__len__()
            return summary
        else:
            return False


class FormhubImportForm(forms.Form):
    formhub_url = forms.URLField(label=_(u"Formhub Form URL"), required=True)

    def fh_import(self):
        if self.is_valid():
            cleaned_url = self.cleaned_data['formhub_url']
            if not cleaned_url.endswith('/form.json'):
                cleaned_url += '/form.json'
            form_data = load_form_from_formhub(cleaned_url)
            if isinstance(form_data, dict):
                fhs = FormhubService(url=cleaned_url,
                    id_string=form_data['id_string'],
                    name=form_data['name'], json=json.dumps(form_data))
                fhs.save()
                return fhs
        return False


class DataValueSetForm(ModelForm):
    class Meta:
        model = DataValueSet


class FHDataElementForm(forms.Form):
    DVS_TUPLE = tuple([(dvs.pk, '%s' % dvs) for dvs in DataValueSet.objects.all()])
    DVS_SELECT_CHOICES = (('', ' ------ '),) + DVS_TUPLE
    DE_TUPLE = tuple([(de.pk, '%s' % de) for de in DataElement.objects.all()])
    DE_CHOICES = (('', ' ------ '),) + DE_TUPLE

    dvs = forms.ChoiceField(widget=forms.Select, choices=DVS_SELECT_CHOICES)
    data_elements = forms.ChoiceField(widget=forms.Select, choices=DE_CHOICES)
    fh_fields = forms.ChoiceField(widget=forms.Select)

    def set_data_elements_choices(self, dvs):
        self.fields['data_elements'].choices = (('', ' ------ '),)\
                    + tuple([(de.pk, '%s' % de)
                        for de in DataElement.objects.filter(data_set=dvs)])

    def set_fh_fields(self, fhs):
        self.fields['fh_fields'].choices = (('', ' ------ '),)\
                                                + fhs.get_form_fields()

main/views.py
import json

from django.contrib.auth.decorators import login_required
from django.db.utils import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.utils.translation import ugettext as _
from main.forms import (DataSetImportForm, FormhubImportForm,
                        DataValueSetForm, FHDataElementForm)

from main.models import (FormhubService, DataQueue, DataValueSet, DataElement,
                         FormDataElement, DataSet)
from main.tasks import process_dqueue
from main.utils import process_data_queue, basic_http_auth


def main(request):
    context = RequestContext(request)
    return render_to_response("index.html", context_instance=context)


def initiate_formhub_request(request, id_string, uuid):
    context = RequestContext(request)
    try:
        fs = FormhubService.objects.get(id_string=id_string)
    except FormhubService.DoesNotExist:
        context.contents = _(u"Unknown Service")
        context.status = False
    else:
        dq, created = DataQueue.objects.get_or_create(service=fs, data_id=uuid)
        dq.processed = False
        dq.save()
        context.status = context.status = True
        context.contents = _(u"OK")
        # call process queue asynchronously
        process_dqueue.delay()
    response = {"status": context.status, "contents": context.contents}
    if 'callback' in request.GET and request.GET.get('callback') != '':
        callback = request.GET.get('callback')
        return HttpResponse("%s(%s)" % (callback, json.dumps(response)),
                            mimetype='application/json')
    return HttpResponse(json.dumps(response), mimetype='application/json')


@basic_http_auth
@login_required
def dataset_import(request):
    context = RequestContext(request)
    context.form = DataSetImportForm()
    if request.method == 'POST':
        form = DataSetImportForm(request.POST)
        context.rs = form.ds_import()
        if context.rs is False:
            context.failed = True
    context.datasets = DataSet.objects.all()
    return render_to_response("dataset-import.html", context_instance=context)


def show_datasets(request):
    context = RequestContext(request)
    context.datasets = DataSet.objects.all()
    return render_to_response("dataset-import.html", context_instance=context)


@login_required
def formhub_import(request):
    context = RequestContext(request)
    context.form = FormhubImportForm()
    if request.method == 'POST':
        form = FormhubImportForm(request.POST)
        try:
            fhs = form.fh_import()
        except IntegrityError, e:
            context.message = _(u"Form has already been uploaded.")
        else:
            if fhs:
                context.fhservice = fhs
            else:
                context.message = _(u"Failed to import from formhub.")
    context.fhforms = FormhubService.objects.all()
    return  render_to_response("formhub-import.html", context_instance=context)


def show_formhub_forms(request):
    context = RequestContext(request)
    context.fhforms = FormhubService.objects.all()
    return  render_to_response("formhub-import.html", context_instance=context)


@login_required
def process_dataqueue(request):
    context = RequestContext(request)
    context.processed = process_data_queue()
    return render_to_response("process-queue.html", context_instance=context)


@login_required
def create_datavalueset(request):
    context = RequestContext(request)
    form = DataValueSetForm()
    if request.method == 'POST':
        form = DataValueSetForm(request.POST)
        if form.is_valid():
            form.save()
            context.success = True
    context.form = form
    return  render_to_response("dvs.html", context_instance=context)


@login_required
def match_datavalueset_to_data_elements(request):
    context = RequestContext(request)
    form = FHDataElementForm()
    context.fde_list = None
    if request.method == 'POST':
        form = FHDataElementForm(request.POST)
        dvs = DataValueSet.objects.get(pk=int(request.POST['dvs']))
        form.set_fh_fields(dvs.service)
        if form.is_valid():
            # form.save()
            de = DataElement.objects.get(pk=form.cleaned_data['data_elements'])
            try:
                fde = FormDataElement()
                fde.data_value_set = dvs
                fde.form_field = form.cleaned_data['fh_fields']
                fde.data_element = de
                fde.save()
            except IntegrityError:
                context.success = False
                context.msg = _(u"Match already saved.")
            else:
                context.success = True
                context.msg = _(u"Successfully saved.")
        else:
            context.success = False
            context.msg = _(u"Failed to save.")
        context.fde_list = list(FormDataElement.objects\
                        .filter(data_value_set=dvs)\
                        .values('data_value_set', 
                                'data_element__name', 'form_field'))
        if request.is_ajax():
            response = {'success': context.success, 'msg': context.msg,
                        'fde_list': context.fde_list}
            return HttpResponse(json.dumps(response))
    context.form = form
    return render_to_response("dvs-to-elements.html", context_instance=context)


def get_matchdvsform(request, dvs_id):
    """
    Returns the form elements string of FHDataElementForm
    given a data value set id
    """
    context = RequestContext(request)
    form = FHDataElementForm(request.GET)
    form.set_data_elements_choices(dvs_id)
    dvs = DataValueSet.objects.get(pk=dvs_id)
    form.set_fh_fields(dvs.service)
    context.form = form
    return  render_to_response("dvs-to-elements-form.html", context_instance=context)

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>F2DHIS2 - Formhub to DHIS2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/static/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="/static/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <script src="/static/bootstrap/assets/js/jquery.js"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
{% block body %}
<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">F2DHIS2</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    {% block content %}
    {% if template %}{% include template %}{% endif %}
    {{ content|safe }}
    {% endblock %}
</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/bootstrap/assets/js/bootstrap.min.js"></script>

</body>
{% endblock %}
</html>

main/templates/dataset-import.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% if form %}
<form action="{% url 'dataset-import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Import" />
</form>
    {% if rs and rs.ds_status %}
        <div class="alert-status">{{ rs.ds_status }}</div>
    {% endif %}
    {% if rs and rs.dataSet %}
        {% trans "Successfully imported" %} {{ rs.dataSet }} {% trans "with" %} {{ rs.dataElements }} {% trans "DataElements and" %} {{ rs.dataElements }} {% trans "OrganizationUnits." %}
    {% elif failed %}
        {% trans "Failed to import DataSet." %}
    {% endif %}
{% endif %}
<table class="table table-condensed">
    <thead>
    <tr>
        <th>DHIS2 DataSet</th>
        <th>Link</th>
    </tr>
    </thead>
    <tbody>
    {% for ds in datasets %}
          <tr>
              <td>{{ ds }}</td>
              <td>{{ ds.url }}</td>
          </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

main/templates/dvs-to-elements-form.html
{% if form %}
{{ form.as_table }}
{% endif %}

main/templates/dvs-to-elements.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
        {% if form %}
<form id="dvsdeform" action="{% url 'match-de' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table id="dvsdeformtable">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>
        {% endif %}
        <div id="alert-status" class="alert-status"></div>
<table class="table table-condensed" id="fde_list">
    <thead>
        <tr>
            <th>DHIS2 Element</th>
            <th>Formhub Form Field</th>
        </tr>
    </thead>
    <tbody id="fde_listbd">
    </tbody>
</table>
    {% if success %}
        {% trans "Successfully saved." %}
    {% endif %}
        <script type="text/javascript">
            $(document).ready(function(){
                var updateFDETable = function(data){
                    $('#fde_list tbody').html('');
                    $.each(data, function(key, value){
                        trow = "<tr><td>" + value.data_element__name;
                        trow += "</td><td>" + value.form_field;
                        trow += "</td></tr>"
                        $('#fde_list tbody').append(trow);
                    });
                };
                var reloadForm = function(){
                    if(this.value != ""){
                        url = '{% url 'match-de-form' 0 %}'.replace(0, this.value)
                        $.get(url + '?dvs='+this.value, function(data){
                            $("#dvsdeformtable").html(data);
                            $("#id_dvs").on("change", reloadForm);
                        })
                    }
                };
                $("#id_dvs").on("change", reloadForm);
                $("#dvsdeform").on("submit", function(evt){
                    evt.preventDefault();
                    if($("#id_dvs").val() == "")
                        return;
                    $.post(this.action, $(this).serialize(), function(data){
                        data = $.parseJSON(data);
                        if(data.msg)
                            $("#alert-status").html(data.msg);
                        if(data.success)
                            $("#dvsdeform").each(function(){
                                this.reset();
                            });
                        if(data.fde_list)
                            updateFDETable(data.fde_list);
                    });
                });

            });
        </script>
{% endblock %}

main/templates/dvs.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
        {% if form %}
<form action="{% url 'create-dvs' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save" />
</form>
        {% endif %}
    {% if message %}
        <div class="alert-status">{{ message }}</div>
    {% endif %}
    {% if success %}
        {% trans "Successfully saved." %}
    {% endif %}
{% endblock %}

main/templates/formhub-import.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% if form %}
<form action="{% url 'fh-import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Import" />
</form>
    {% if message %}
        <div class="alert-status">{{ message }}</div>
    {% endif %}
    {% if fhservice %}
        {% trans "Successfully imported" %} {{ fhservice }}: {{ fhservice.url }}.
    {% endif %}
{% endif %}

<table class="table table-condensed">
    <thead>
    <tr>
        <th>FormHub Form</th>
        <th>Link</th>
    </tr>
    </thead>
    <tbody>
    {% for fh in fhforms %}
    <tr>
        <td>{{ fh }}</td>
        <td>{{ fh.url }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<h1>Formhub to DHIS2 Utility</h1>

<div class="row-fluid">
    <div class="span4">
        <h4><a href="{% url 'dataset-import' %}">1. Import DHIS2 DataSet</a></h4>

        <p>e.g http://apps.dhis2.org/demo/api/dataSets/aLpVgfXiz0f
            <br/>
            This imports the DataSet, attached DataElements and Organization
            Units
        </p>
        <a href="{% url 'datasets' %}">View Imported Datasets</a>
    </div>
    <div class="span4">
        <h4><a href="{% url 'fh-import' %}">2. Import Formhub Form</a></h4>

        <p>e.g http://formhub.org/ukanga/forms/dhis2form
            <br/>
        <ul>
            <li>this saves the form url, name, id_string and form json</li>
            <li>this form has the fields that you would want to push to DHIS2
            </li>
            <li>one of the fields should be a datefield named period</li>
            <li>currently also ensure that both form and data are shared i.e
                open access
            </li>
        </ul>
        </p>
        <a href="{% url 'fh-forms' %}">View Imported Forms</a>
    </div>
    <div class="span4">
        <h4><a href="{% url 'create-dvs' %}">3. Create a Value DataSet</a></h4>

        <p>Links the Formhub form to the DHIS2 DataSet.
        </p>
    </div>
</div>
        &nbsp;
<div class="row-fluid">

    <div class="span4">
        <h4><a href="{% url 'match-de' %}"> 4. Specify form data elements</a></h4>

        <p>
        <ul>
            <li>this links a DataValueSet with the form fields to dhis2
                DataElements
            </li>
            <li>e.g formhub form field 'population_under_5' to "Total population
                < 5 years (DTtCy7Nx5jH)"
            </li>
            <li>multiple form data elements are added to the DataValueSet</li>
        </ul>
        </p>
    </div>
    <div class="span4">
        <h4>5. Initiate Formhub Data Request, this should be the link formhub
            should hit for every submission</h4>

        <p>
        <ul>
            <li>i.e curl http://fh.ukanga.com/%(id_string)s/post/%(uuid)s<br/>
                e.g curl http://fh.ukanga.com/dhis2form/post/118024
            </li>
            <li>- you should get a response similar to <em>{"status": true,
                "contents": "OK"}</em>.<br/>
                This means that the data is now queued and would be processed
                asynchronously almost immediately
            </li>
            <li>To find out the _id of a submission currently you need to access
                the data on formhub via api
                e.g http://formhub.org/ukanga/forms/dhis2form/api, look for
                "_id": 118024 where 118024 is the id you seek.
            </li>
        </ul>
        </p>
    </div>
    <div class="span4">
        <h4>6. Check on DHIS2 deployment for posted data</h4>

        <p>If success full you should check
            dhis2 link i.e http://apps.dhis2.org/demo/dhis-web-dataentry/index.action on
            data entry section to see if your data was posted.
            <em>Note:</em>
            <ul><li>Organization</li>
            <li>The DataSet for your DataValueSet</li>
            <li>The Date/Period which can be the year, month and possibly date you
            had specified in your form submission</li>
        </ul>
        

    </div>
</div>
{% endblock %}

main/templates/process-queue.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% trans "Processed" %} {{ processed }} {% trans "records." %}
{% endblock %}